export default {
  cart: [],
  buyer: [],
  orders: [],
  products: [
    {
      'id': '1',
      'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg',
      'title': 'Bulbasaur',
      'price': 25,
      'description': 'Este Pokémon nace con una semilla en el lomo, que brota con el paso del tiempo.',
    },
    {
      'id': '2',
      'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg',
      'title': 'Ivysaur',
      'price': 35,
      'description': 'Cuando le crece bastante el bulbo del lomo, pierde la capacidad de erguirse sobre las patas traseras.',
    },
    {
      'id': '3',
      'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/3.svg',
      'title': 'Venusaur',
      'price': 45,
      'description': 'La planta florece cuando absorbe energía solar, lo cual le obliga a buscar siempre la luz del sol.',
    },
    {
      'id': '4',
      'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/4.svg',
      'title': 'Charmander',
      'price': 25,
      'description': 'Prefiere las cosas calientes. Dicen que cuando llueve le sale vapor de la punta de la cola.',
    },
    {
      'id': '5',
      'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/5.svg',
      'title': 'Charmeleon',
      'price': 30,
      'description': 'Este Pokémon de naturaleza agresiva ataca en combate con su cola llameante y hace trizas al rival con sus afiladas garras.',
    },
    {
      'id': '6',
      'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6.svg',
      'title': 'Charizard',
      'price': 35,
      'description': 'Escupe un fuego tan caliente que funde las rocas. Causa incendios forestales sin querer.',
    },
    {
      'id': '7',
      'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/7.svg',
      'title': 'Squirtle',
      'price': 20,
      'description': 'Cuando retrae su largo cuello en el caparazón, dispara agua a una presión increíble.',
    },
    {
      'id': '8',
      'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/8.svg',
      'title': 'Wartortle',
      'price': 35,
      'description': 'Se lo considera un símbolo de longevidad. Los ejemplares más ancianos tienen musgo sobre el caparazón.',
    },
    {
      'id': '9',
      'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/9.svg',
      'title': 'Blastoise',
      'price': 35,
      'description': 'Para acabar con su enemigo, lo aplasta con el peso de su cuerpo. En momentos de apuro, se esconde en el caparazón.',
    },
  ],
};